export type IntegrationProvider = 'shopify' | 'slack' | 'airtable' | 'gmail' | 'google_drive' | 'email';

export type IntegrationRecord = {
  provider: IntegrationProvider;
  credentials: Record<string, string>;
};

export function requiredProvidersFromWorkflow(workflow: unknown): IntegrationProvider[] {
  const nodes = ((workflow as { nodes?: Array<{ type?: string }> } | null)?.nodes ?? []);
  const required = new Set<IntegrationProvider>();

  for (const node of nodes) {
    const type = (node.type ?? '').toLowerCase();
    if (type.includes('webhook')) continue;

    if (type.includes('shopify')) required.add('shopify');
    if (type.includes('slack')) required.add('slack');
    if (type.includes('airtable')) required.add('airtable');
    if (type.includes('smtp') || type.includes('email') || type.includes('gmail')) required.add('gmail');
    if (type.includes('drive')) required.add('google_drive');
  }

  return Array.from(required);
}

function replaceEnvTokens(raw: string, integrations: Record<IntegrationProvider, Record<string, string> | undefined>): string {
  const shopify = integrations.shopify;
  const slack = integrations.slack;
  const airtable = integrations.airtable;
  const email = integrations.gmail ?? integrations.email;

  return raw
    .replace(/\{\{\s*\$env\.SHOPIFY_ACCESS_TOKEN\s*\}\}/g, shopify?.admin_access_token ?? shopify?.api_key ?? '')
    .replace(/\{\{\s*\$env\.SHOPIFY_API_KEY\s*\}\}/g, shopify?.admin_access_token ?? shopify?.api_key ?? '')
    .replace(/\{\{\s*\$env\.SHOPIFY_STORE_URL\s*\}\}/g, shopify?.shop_domain ?? shopify?.store_url ?? '')
    .replace(/\{\{\s*\$env\.SLACK_WEBHOOK_URL\s*\}\}/g, slack?.webhook_url ?? '')
    .replace(/\{\{\s*\$env\.AIRTABLE_API_KEY\s*\}\}/g, airtable?.airtable_token ?? airtable?.api_key ?? '')
    .replace(/\{\{\s*\$env\.AIRTABLE_BASE_ID\s*\}\}/g, airtable?.base_id ?? '')
    // Also support user.* placeholders generated by templates/prompts.
    .replace(/\{\{\s*user\.shopify\.api[_-]?key\s*\}\}/gi, shopify?.admin_access_token ?? shopify?.api_key ?? '')
    .replace(/\{\{\s*user\.shopify\.token\s*\}\}/gi, shopify?.admin_access_token ?? shopify?.api_key ?? '')
    .replace(/\{\{\s*user\.shopify\.store[_-]?url\s*\}\}/gi, shopify?.shop_domain ?? shopify?.store_url ?? '')
    .replace(/\{\{\s*user\.slack\.webhook\s*\}\}/gi, slack?.webhook_url ?? '')
    .replace(/\{\{\s*user\.slack\.webhook[_-]?url\s*\}\}/gi, slack?.webhook_url ?? '')
    .replace(/\{\{\s*user\.airtable\.api[_-]?key\s*\}\}/gi, airtable?.airtable_token ?? airtable?.api_key ?? '')
    .replace(/\{\{\s*user\.airtable\.base[_-]?id\s*\}\}/gi, airtable?.base_id ?? '')
    .replace(/\{\{\s*\$env\.SMTP_HOST\s*\}\}/g, email?.smtp_host ?? '')
    .replace(/\{\{\s*\$env\.SMTP_PORT\s*\}\}/g, email?.smtp_port ?? '')
    .replace(/\{\{\s*\$env\.SMTP_USER\s*\}\}/g, email?.smtp_user ?? '')
    .replace(/\{\{\s*\$env\.SMTP_PASS\s*\}\}/g, email?.smtp_pass ?? '')
    .replace(/\{\{\s*\$env\.EMAIL_FROM\s*\}\}/g, email?.from_email ?? '')
    .replace(/\{\{\s*user\.email\.smtp[_-]?host\s*\}\}/gi, email?.smtp_host ?? '')
    .replace(/\{\{\s*user\.email\.smtp[_-]?port\s*\}\}/gi, email?.smtp_port ?? '')
    .replace(/\{\{\s*user\.email\.smtp[_-]?user\s*\}\}/gi, email?.smtp_user ?? '')
    .replace(/\{\{\s*user\.email\.smtp[_-]?pass\s*\}\}/gi, email?.smtp_pass ?? '')
    .replace(/\{\{\s*user\.email\.from\s*\}\}/gi, email?.from_email ?? '');
}

function deepInject(value: unknown, integrations: Record<IntegrationProvider, Record<string, string> | undefined>): unknown {
  if (typeof value === 'string') {
    return replaceEnvTokens(value, integrations);
  }

  if (Array.isArray(value)) {
    return value.map(v => deepInject(v, integrations));
  }

  if (value && typeof value === 'object') {
    const output: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      output[key] = deepInject(val, integrations);
    }
    return output;
  }

  return value;
}

/**
 * Injects user credentials into generated n8n JSON.
 * This keeps all credential handling server-side.
 */
export function injectCredentialsIntoWorkflow(
  workflowJson: unknown,
  integrationRows: IntegrationRecord[]
): Record<string, unknown> {
  const workflow = JSON.parse(JSON.stringify(workflowJson ?? {})) as {
    nodes?: Array<Record<string, unknown>>;
  };

  const byProvider: Record<IntegrationProvider, Record<string, string> | undefined> = {
    shopify: integrationRows.find(r => r.provider === 'shopify')?.credentials,
    slack: integrationRows.find(r => r.provider === 'slack')?.credentials,
    airtable: integrationRows.find(r => r.provider === 'airtable')?.credentials,
    google_drive: undefined,
    gmail: integrationRows.find(r => r.provider === 'gmail')?.credentials ?? integrationRows.find(r => r.provider === 'email')?.credentials,
    email: integrationRows.find(r => r.provider === 'gmail')?.credentials ?? integrationRows.find(r => r.provider === 'email')?.credentials,
  };

  workflow.nodes = (workflow.nodes ?? []).map(node => {
    const type = String(node.type ?? '').toLowerCase();
    const nextNode = deepInject(node, byProvider) as Record<string, unknown>;

    if (type.includes('shopify') && byProvider.shopify) {
      const params = (nextNode.parameters as Record<string, unknown> | undefined) ?? {};
      params.accessToken = byProvider.shopify.admin_access_token ?? byProvider.shopify.api_key ?? params.accessToken;
      params.storeUrl = byProvider.shopify.shop_domain ?? byProvider.shopify.store_url ?? params.storeUrl;
      nextNode.parameters = params;
    }

    if (type.includes('airtable') && byProvider.airtable) {
      const params = (nextNode.parameters as Record<string, unknown> | undefined) ?? {};
      params.apiKey = byProvider.airtable.airtable_token ?? byProvider.airtable.api_key ?? params.apiKey;
      params.base = params.base ?? byProvider.airtable.base_id;
      params.table = params.table ?? byProvider.airtable.table_name;
      nextNode.parameters = params;
    }

    // Convert Slack node to Webhook POST when only incoming webhook is provided.
    if (type.includes('slack') && byProvider.slack?.webhook_url) {
      const text = (((nextNode.parameters as Record<string, unknown> | undefined)?.text as string) ?? 'Workflow notification');
      nextNode.type = 'n8n-nodes-base.httpRequest';
      nextNode.typeVersion = 4;
      nextNode.name = String(nextNode.name ?? 'Slack Webhook');
      nextNode.parameters = {
        method: 'POST',
        url: byProvider.slack.webhook_url,
        sendBody: true,
        contentType: 'json',
        jsonBody: JSON.stringify({ text }),
      };
    }

    return nextNode;
  });

  return workflow as Record<string, unknown>;
}
