'use client';

import { useState } from 'react';
import { Brain, Layers, ShieldCheck, Zap, CircleCheck as CheckCircle2, TriangleAlert as AlertTriangle, Info, Clock, Package, ArrowRight, Download, Rocket, Copy, Check, RefreshCw, CircleAlert as AlertCircle, ExternalLink, KeyRound, FileJson, Sparkles, Bot, Circle as XCircle, Crown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PlannerResult, AutomationPlan } from '@/lib/planner';
import { ValidationResult } from '@/lib/validator';
import { BLOCKS } from '@/lib/blocks';
import { SetupWizard, DeploymentLifecycle } from '@/components/builder/setup-wizard';
import { OneClickDeploy, ExecutionHealthPanel, LiveDeployResult } from '@/components/builder/one-click-deploy';
import { cn } from '@/lib/utils';

type ArchitectTab = 'plan' | 'compose' | 'validate';

interface ArchitectPanelProps {
  plannerResult: PlannerResult;
  validation: ValidationResult;
  onDeploy?: () => void;
  onDownload?: () => void;
  isDeploying?: boolean;
  deployedUrl?: string | null;
  deployedWorkflowId?: string | null;
  deploymentLifecycle?: DeploymentLifecycle;
  onLifecycleChange?: (next: DeploymentLifecycle) => void;
  onCheckActivation?: () => Promise<boolean>;
  isCheckingActivation?: boolean;
  /** Called when one-click live deploy completes */
  onLiveDeploy?: (result: LiveDeployResult) => void;
  /** Result of a completed live deploy (for health panel persistence across tab switches) */
  liveDeployResult?: LiveDeployResult | null;
  className?: string;
  /** Whether the current user is on a Pro plan */
  isPro?: boolean;
  /** Called when user clicks upgrade from within the panel */
  onUpgrade?: () => void;
}

// ── BLOCK CATEGORY COLORS ────────────────────────────────────────────────────

const BLOCK_CATEGORY_COLORS: Record<string, string> = {
  trigger:   'bg-blue-500/15 border-blue-500/30 text-blue-400',
  transform: 'bg-cyan-500/15 border-cyan-500/30 text-cyan-400',
  condition: 'bg-amber-500/15 border-amber-500/30 text-amber-400',
  action:    'bg-emerald-500/15 border-emerald-500/30 text-emerald-400',
  delay:     'bg-orange-500/15 border-orange-500/30 text-orange-400',
  error:     'bg-red-500/15 border-red-500/30 text-red-400'
};

const COMPLEXITY_COLORS: Record<string, string> = {
  simple:   'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
  moderate: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
  complex:  'text-red-400 bg-red-500/10 border-red-500/20'
};

const VALIDATION_SEVERITY_STYLES: Record<string, { icon: React.ElementType; color: string; bg: string }> = {
  error:   { icon: AlertCircle, color: 'text-red-400', bg: 'bg-red-500/10 border-red-500/20' },
  warning: { icon: AlertTriangle, color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/20' },
  info:    { icon: Info, color: 'text-blue-400', bg: 'bg-blue-500/10 border-blue-500/20' }
};

// ── COPY BUTTON ──────────────────────────────────────────────────────────────

function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  async function handleCopy() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }
  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground px-2 py-1 rounded-md hover:bg-muted/50 transition-colors"
    >
      {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
      {copied ? 'Copied!' : label}
    </button>
  );
}

// ── PLANNER MODE BADGE ────────────────────────────────────────────────────────

const PLANNER_MODE_CONFIG = {
  openai: {
    label: 'OpenAI Structured Planner',
    icon: Sparkles,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10 border-emerald-500/20',
    description: 'Plan generated by GPT-4o with structured output'
  },
  deterministic: {
    label: 'Deterministic Planner',
    icon: Brain,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10 border-blue-500/20',
    description: 'Plan generated by keyword pattern matching'
  },
  deterministic_fallback: {
    label: 'Deterministic Fallback',
    icon: Bot,
    color: 'text-amber-400',
    bg: 'bg-amber-500/10 border-amber-500/20',
    description: 'OpenAI unavailable — used keyword planner instead'
  }
} as const;

// ── PLAN TAB ──────────────────────────────────────────────────────────────────

function PlanTab({ plan }: { plan: AutomationPlan }) {
  const modeConfig = plan.plannerModeUsed ? PLANNER_MODE_CONFIG[plan.plannerModeUsed] : PLANNER_MODE_CONFIG.deterministic;
  const ModeIcon = modeConfig.icon;

  return (
    <div className="space-y-4">
      {/* Planner mode badge */}
      <div className={cn('rounded-lg border px-3 py-2 flex items-center gap-2.5', modeConfig.bg)}>
        <ModeIcon className={cn('w-3.5 h-3.5 flex-shrink-0', modeConfig.color)} />
        <div className="flex-1 min-w-0">
          <p className={cn('text-xs font-semibold', modeConfig.color)}>{modeConfig.label}</p>
          <p className="text-[11px] text-muted-foreground">{modeConfig.description}</p>
        </div>
        {plan.confidenceReason && (
          <span className="text-xs text-muted-foreground/70 hidden sm:block max-w-[140px] truncate text-right">
            {plan.confidence}% — {plan.confidenceReason}
          </span>
        )}
      </div>

      {/* Unsupported requirements — show prominently if any */}
      {plan.unsupportedRequirements && plan.unsupportedRequirements.length > 0 && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-3 space-y-2">
          <div className="flex items-center gap-2">
            <XCircle className="w-4 h-4 text-red-400 flex-shrink-0" />
            <p className="text-xs font-semibold text-red-400">Unsupported Requirements</p>
          </div>
          <p className="text-[11px] text-muted-foreground">
            These parts of your request cannot be fulfilled with available blocks. The plan below is the closest available automation.
          </p>
          <ul className="space-y-1">
            {plan.unsupportedRequirements.map((req, i) => (
              <li key={i} className="flex items-start gap-2 text-xs">
                <span className="text-red-400 flex-shrink-0 mt-0.5">✗</span>
                <span className="text-muted-foreground">{req}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Plan header */}
      <div className="rounded-xl border border-border bg-muted/20 p-4">
        <div className="flex items-start justify-between gap-3 mb-3">
          <div>
            <h3 className="text-sm font-semibold">{plan.title}</h3>
            <p className="text-xs text-muted-foreground mt-0.5">{plan.description}</p>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <span className={cn('text-xs px-2 py-0.5 rounded-full border font-medium', COMPLEXITY_COLORS[plan.complexity])}>
              {plan.complexity}
            </span>
            <span className="text-xs px-2 py-0.5 rounded-full border border-border bg-muted text-muted-foreground font-medium">
              {plan.confidence}%
            </span>
          </div>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed italic"
          dangerouslySetInnerHTML={{ __html: plan.planReasoning.replace(/\*\*(.*?)\*\*/g, '<strong class="text-foreground">$1</strong>') }}
        />
      </div>

      {/* Assumptions */}
      {plan.assumptions && plan.assumptions.length > 0 && (
        <div className="rounded-lg border border-border bg-muted/10 p-3 space-y-1.5">
          <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
            <Info className="w-3 h-3" />
            Assumptions
          </p>
          <ul className="space-y-1">
            {plan.assumptions.map((assumption, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                <span className="text-muted-foreground/50 flex-shrink-0 mt-0.5">→</span>
                {assumption}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Trigger */}
      <div>
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2">Trigger</p>
        <div className="flex items-center gap-3 rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
          <div className="w-7 h-7 rounded-lg bg-blue-500/20 flex items-center justify-center flex-shrink-0">
            <Zap className="w-3.5 h-3.5 text-blue-400" />
          </div>
          <div className="flex-1">
            <p className="text-sm font-medium">{BLOCKS[plan.trigger.blockId]?.name || plan.trigger.type}</p>
            <p className="text-xs text-muted-foreground">{plan.trigger.description}</p>
          </div>
          <span className="text-xs text-blue-400 font-mono">trigger</span>
        </div>
      </div>

      {/* Steps */}
      <div>
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2">
          Steps ({plan.steps.length})
        </p>
        <div className="space-y-2">
          {plan.steps.map((step, i) => {
            const block = BLOCKS[step.blockId];
            const categoryColor = BLOCK_CATEGORY_COLORS[block?.category || 'action'];
            return (
              <div key={step.stepId} className="flex items-center gap-3">
                <div className="flex flex-col items-center flex-shrink-0">
                  <div className="w-5 h-5 rounded-full border border-border bg-muted flex items-center justify-center text-[10px] font-mono text-muted-foreground">
                    {i + 1}
                  </div>
                  {i < plan.steps.length - 1 && (
                    <div className="w-px flex-1 bg-border min-h-[8px]" />
                  )}
                </div>
                <div className={cn('flex-1 rounded-lg border p-2.5 flex items-center gap-2.5', categoryColor)}>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-medium">{step.name}</p>
                    <p className="text-xs opacity-70 truncate">{step.description}</p>
                  </div>
                  <div className="flex items-center gap-1 flex-shrink-0">
                    <span className="text-[10px] font-mono opacity-60">{block?.category}</span>
                    {step.required && (
                      <span className="text-[10px] px-1 rounded bg-current/10 opacity-70">required</span>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Required credentials */}
      {plan.requiredCredentials && plan.requiredCredentials.length > 0 && (
        <div>
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <KeyRound className="w-3 h-3" />
            Required Credentials
          </p>
          <div className="flex flex-wrap gap-1.5">
            {plan.requiredCredentials.map(cred => (
              <span key={cred} className="text-xs px-2 py-1 rounded-lg border border-amber-500/20 bg-amber-500/5 text-amber-400">
                {cred}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Integrations */}
      {plan.integrations.length > 0 && (
        <div>
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2">Integrations</p>
          <div className="flex flex-wrap gap-1.5">
            {plan.integrations.map(integration => (
              <span key={integration} className="text-xs px-2 py-1 rounded-lg border border-border bg-muted/30 text-muted-foreground">
                {integration}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── COMPOSE TAB ───────────────────────────────────────────────────────────────

function ComposeTab({ plannerResult }: { plannerResult: PlannerResult }) {
  const { composition, n8nJson, envConfig } = plannerResult;
  const [view, setView] = useState<'visual' | 'json' | 'env'>('visual');

  const nodeCount = composition.blocks.length;
  const maxX = Math.max(...composition.blocks.map(b => b.position[0])) + 200;
  const svgWidth = Math.max(600, maxX + 100);
  const svgHeight = 200;

  return (
    <div className="space-y-3">
      {/* View toggle */}
      <div className="flex gap-1 p-1 rounded-lg bg-muted/30 border border-border">
        {(['visual', 'json', 'env'] as const).map(v => (
          <button
            key={v}
            onClick={() => setView(v)}
            className={cn(
              'flex-1 text-xs py-1.5 rounded-md font-medium transition-colors',
              view === v ? 'bg-background shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
            )}
          >
            {v === 'visual' ? 'Visual Flow' : v === 'json' ? 'n8n JSON' : '.env Config'}
          </button>
        ))}
      </div>

      {view === 'visual' && (
        <div className="rounded-xl border border-border bg-muted/10 overflow-hidden">
          {/* Stats bar */}
          <div className="flex items-center gap-4 px-4 py-2.5 border-b border-border bg-muted/20 text-xs text-muted-foreground">
            <span className="flex items-center gap-1"><Layers className="w-3 h-3" />{nodeCount} blocks</span>
            <span className="flex items-center gap-1"><ArrowRight className="w-3 h-3" />{composition.connections.length} connections</span>
            <span className="flex items-center gap-1"><Package className="w-3 h-3" />{composition.envVars.length} env vars</span>
          </div>

          {/* SVG canvas */}
          <div className="overflow-x-auto">
            <svg
              width={svgWidth}
              height={svgHeight}
              className="block"
              style={{ minWidth: '100%' }}
            >
              {/* Connection lines */}
              {composition.connections.map((conn, i) => {
                const from = composition.blocks.find(b => b.instanceId === conn.fromInstanceId);
                const to = composition.blocks.find(b => b.instanceId === conn.toInstanceId);
                if (!from || !to) return null;

                const x1 = from.position[0] + 140;
                const y1 = from.position[1] - 200 + svgHeight / 2 + 20;
                const x2 = to.position[0];
                const y2 = to.position[1] - 200 + svgHeight / 2 + 20;
                const mx = (x1 + x2) / 2;

                return (
                  <g key={i}>
                    <path
                      d={`M ${x1} ${y1} C ${mx} ${y1} ${mx} ${y2} ${x2} ${y2}`}
                      fill="none"
                      stroke="hsl(var(--border))"
                      strokeWidth="1.5"
                    />
                    <circle cx={x2} cy={y2} r="3" fill="hsl(var(--border))" />
                  </g>
                );
              })}

              {/* Nodes */}
              {composition.blocks.map(placed => {
                const block = placed.block;
                const catColor = block.category === 'trigger' ? '#60a5fa'
                  : block.category === 'transform' ? '#22d3ee'
                  : block.category === 'condition' ? '#f59e0b'
                  : block.category === 'delay' ? '#fb923c'
                  : block.category === 'error' ? '#f87171'
                  : '#4ade80';
                const bx = placed.position[0];
                const by = svgHeight / 2 - 20;

                return (
                  <g key={placed.instanceId}>
                    <rect
                      x={bx}
                      y={by - 8}
                      width={140}
                      height={56}
                      rx={8}
                      fill="hsl(var(--card))"
                      stroke={catColor}
                      strokeWidth="1.5"
                      strokeOpacity="0.4"
                    />
                    <rect
                      x={bx}
                      y={by - 8}
                      width={140}
                      height={56}
                      rx={8}
                      fill={catColor}
                      fillOpacity="0.06"
                    />
                    <text x={bx + 12} y={by + 12} fontSize="10" fill={catColor} fontWeight="600" fontFamily="monospace">
                      {block.category.toUpperCase()}
                    </text>
                    <text x={bx + 12} y={by + 28} fontSize="11" fill="hsl(var(--foreground))" fontWeight="500">
                      {block.name.length > 16 ? block.name.slice(0, 15) + '…' : block.name}
                    </text>
                    <circle cx={bx + 140} cy={by + 20} r="4" fill={catColor} fillOpacity="0.6" />
                    <circle cx={bx} cy={by + 20} r="4" fill={catColor} fillOpacity="0.6" />
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Legend */}
          <div className="flex flex-wrap gap-x-4 gap-y-1 px-4 py-2.5 border-t border-border bg-muted/10">
            {Object.entries(BLOCK_CATEGORY_COLORS).map(([cat, cls]) => (
              <span key={cat} className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                <span className={cn('w-2 h-2 rounded-full border', cls)} />
                {cat}
              </span>
            ))}
          </div>
        </div>
      )}

      {view === 'json' && (
        <div className="rounded-xl border border-border bg-muted/10 overflow-hidden">
          <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-muted/20">
            <span className="text-xs font-medium text-muted-foreground">n8n Workflow JSON</span>
            <CopyButton text={JSON.stringify(n8nJson, null, 2)} label="Copy JSON" />
          </div>
          <pre className="text-xs font-mono p-4 overflow-auto max-h-64 text-muted-foreground leading-relaxed">
            {JSON.stringify(n8nJson, null, 2)}
          </pre>
        </div>
      )}

      {view === 'env' && (
        <div className="rounded-xl border border-border bg-muted/10 overflow-hidden">
          <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-muted/20">
            <span className="text-xs font-medium text-muted-foreground">.env Configuration</span>
            <CopyButton text={envConfig} label="Copy .env" />
          </div>
          <pre className="text-xs font-mono p-4 overflow-auto max-h-64 text-muted-foreground leading-relaxed whitespace-pre">
            {envConfig}
          </pre>
        </div>
      )}

      {/* Dependency list */}
      {plannerResult.dependencies.length > 0 && (
        <div>
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-2">Required Credentials</p>
          <div className="space-y-1.5">
            {plannerResult.dependencies.map(dep => (
              <div key={dep.service} className="flex items-center gap-2.5 rounded-lg border border-border bg-muted/10 px-3 py-2">
                <Package className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium">{dep.service}</p>
                  <p className="text-xs text-muted-foreground truncate">{dep.description}</p>
                </div>
                {dep.setupUrl && (
                  <a href={dep.setupUrl} target="_blank" rel="noopener noreferrer"
                    className="text-primary hover:text-primary/80 transition-colors flex-shrink-0">
                    <ExternalLink className="w-3 h-3" />
                  </a>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── VALIDATE TAB ─────────────────────────────────────────────────────────────

function ValidateTab({
  validation,
  plannerResult,
  onDeploy,
  onDownload,
  isDeploying,
  deployedUrl,
  onLiveDeploy,
  liveDeployResult,
  hasApprovalNode,
  isPro,
  onUpgrade,
}: {
  validation: ValidationResult;
  plannerResult: PlannerResult;
  onDeploy?: () => void;
  onDownload?: () => void;
  isDeploying?: boolean;
  deployedUrl?: string | null;
  onLiveDeploy?: (result: LiveDeployResult) => void;
  liveDeployResult?: LiveDeployResult | null;
  hasApprovalNode: boolean;
  isPro?: boolean;
  onUpgrade?: () => void;
}) {
  const scoreColor = validation.score >= 80 ? 'text-emerald-400' : validation.score >= 60 ? 'text-amber-400' : 'text-red-400';
  const scoreBg = validation.score >= 80 ? 'from-emerald-500/20 to-emerald-500/5' : validation.score >= 60 ? 'from-amber-500/20 to-amber-500/5' : 'from-red-500/20 to-red-500/5';

  const structuralIssues = validation.issues.filter(i => i.code !== 'CREDENTIAL_REQUIRED');

  return (
    <div className="space-y-4">
      {/* Score card */}
      <div className={cn('rounded-xl border border-border bg-gradient-to-b p-4', scoreBg)}>
        <div className="flex items-center justify-between mb-3">
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Deployment Readiness</p>
            <p className="text-xs text-muted-foreground mt-0.5">{validation.summary}</p>
          </div>
          <div className="text-right">
            <p className={cn('text-3xl font-bold', scoreColor)}>{validation.score}</p>
            <p className="text-xs text-muted-foreground">/ 100</p>
          </div>
        </div>

        <div className="w-full h-2 rounded-full bg-muted/40 overflow-hidden">
          <div
            className={cn('h-full rounded-full transition-all duration-700',
              validation.score >= 80 ? 'bg-emerald-400' : validation.score >= 60 ? 'bg-amber-400' : 'bg-red-400'
            )}
            style={{ width: `${validation.score}%` }}
          />
        </div>

        <div className="flex items-center gap-4 mt-3 text-xs text-muted-foreground flex-wrap">
          <span className="flex items-center gap-1">
            <Clock className="w-3 h-3" />
            Setup: {validation.estimatedSetupTime}
          </span>
          <span className={cn('flex items-center gap-1', validation.importable ? 'text-emerald-400' : 'text-red-400')}>
            <FileJson className="w-3 h-3" />
            {validation.importable ? 'JSON importable' : 'Import issues'}
          </span>
          <span className={cn('flex items-center gap-1', validation.valid ? 'text-emerald-400' : 'text-red-400')}>
            {validation.valid ? <CheckCircle2 className="w-3 h-3" /> : <AlertCircle className="w-3 h-3" />}
            {validation.valid ? 'Structure valid' : `${validation.errors.length} error${validation.errors.length > 1 ? 's' : ''}`}
          </span>
        </div>
      </div>

      {/* Credential requirements — shown prominently as a setup checklist, not errors */}
      {validation.credentialsRequired.length > 0 && (
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 space-y-3">
          <div className="flex items-center gap-2">
            <KeyRound className="w-4 h-4 text-amber-400 flex-shrink-0" />
            <p className="text-xs font-semibold text-amber-400">
              {validation.credentialsRequired.length} credential{validation.credentialsRequired.length > 1 ? 's' : ''} required — link in n8n after deployment
            </p>
          </div>
          <div className="space-y-2">
            {validation.credentialsRequired.map(cred => (
              <div key={cred.service} className="flex items-start gap-2.5 rounded-lg border border-border/60 bg-background/50 px-3 py-2">
                <div className="w-4 h-4 rounded-full border-2 border-amber-500/50 flex-shrink-0 mt-0.5" />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium">{cred.service}</p>
                  <p className="text-[11px] text-muted-foreground">{cred.description}</p>
                  <p className="text-[11px] text-muted-foreground/70 font-mono mt-0.5">
                    n8n type: <span className="text-foreground/60">{cred.n8nCredentialType}</span>
                  </p>
                  <p className="text-[11px] text-muted-foreground/60">
                    Used by: {cred.nodeNames.join(', ')}
                  </p>
                </div>
                {cred.setupUrl && (
                  <a href={cred.setupUrl} target="_blank" rel="noopener noreferrer"
                    className="text-amber-400 hover:text-amber-300 transition-colors flex-shrink-0 mt-0.5">
                    <ExternalLink className="w-3 h-3" />
                  </a>
                )}
              </div>
            ))}
          </div>
          <p className="text-[11px] text-muted-foreground/70">
            Workflow will be deployed as an inactive draft. No fake credential IDs are embedded in the JSON — link credentials in n8n UI after import, then activate.
          </p>
        </div>
      )}

      {/* Structural issues (excluding credential items which have their own section) */}
      {structuralIssues.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Validation Results</p>
          {structuralIssues.map((issue, i) => {
            const cfg = VALIDATION_SEVERITY_STYLES[issue.severity];
            const IssueIcon = cfg.icon;
            return (
              <div key={i} className={cn('rounded-lg border p-3 flex items-start gap-2.5', cfg.bg)}>
                <IssueIcon className={cn('w-3.5 h-3.5 flex-shrink-0 mt-0.5', cfg.color)} />
                <div className="flex-1 min-w-0">
                  <p className={cn('text-xs font-medium', cfg.color)}>{issue.message}</p>
                  {issue.fix && (
                    <p className="text-xs text-muted-foreground mt-0.5">{issue.fix}</p>
                  )}
                </div>
                {issue.autoFixable && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-muted/50 text-muted-foreground flex-shrink-0">auto-fixable</span>
                )}
              </div>
            );
          })}
        </div>
      )}

      {structuralIssues.length === 0 && (
        <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-3 flex items-center gap-2.5">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
          <p className="text-xs text-emerald-400 font-medium">All structural checks passed. Workflow JSON is n8n-importable.</p>
        </div>
      )}

      {/* Live health panel — shown when live deploy completed */}
      {liveDeployResult && liveDeployResult.stage === 'complete' && (
        <ExecutionHealthPanel result={liveDeployResult} />
      )}

      {/* Deploy actions */}
      {!liveDeployResult && (
        <>
          {deployedUrl ? (
            <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-3 space-y-2">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <p className="text-sm font-medium text-emerald-400">Deployed as inactive draft</p>
              </div>
              <p className="text-xs text-muted-foreground">
                {validation.activationBlocked
                  ? 'Link credentials in n8n, then manually activate the workflow.'
                  : 'Workflow is ready to activate in n8n.'}
              </p>
              <a
                href={deployedUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1.5 text-xs text-emerald-400 hover:underline"
              >
                Open in n8n
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          ) : validation.deploymentReady ? (
            <div className="space-y-3">
              {/* Pro gate — shown to free users instead of live deploy */}
              {!isPro && onUpgrade && (
                <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 space-y-3">
                  <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center flex-shrink-0">
                      <Crown className="w-4 h-4 text-amber-400" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-amber-400">Pro required to deploy</p>
                      <p className="text-xs text-muted-foreground">One-click deploy to your n8n instance is a Pro feature.</p>
                    </div>
                  </div>
                  <Button
                    onClick={onUpgrade}
                    className="w-full gap-2 bg-amber-500 hover:bg-amber-400 text-black font-semibold"
                    size="sm"
                  >
                    <Crown className="w-3.5 h-3.5" />
                    Upgrade to Pro — $19
                  </Button>
                  <p className="text-[11px] text-muted-foreground text-center">
                    One-time payment. Download workflow JSON below — free forever.
                  </p>
                  {onDownload && (
                    <Button variant="ghost" onClick={onDownload} className="w-full gap-2 text-xs" size="sm">
                      <Download className="w-3.5 h-3.5" />
                      Download Workflow JSON (Free)
                    </Button>
                  )}
                </div>
              )}

              {/* One-click live deploy — primary action (Pro only) */}
              {onLiveDeploy && isPro && (
                <div className="rounded-xl border border-primary/20 bg-primary/5 p-4">
                  <OneClickDeploy
                    workflowName={plannerResult.plan.title}
                    workflowJson={plannerResult.n8nJson}
                    credentialsRequired={validation.credentialsRequired}
                    hasApprovalNode={hasApprovalNode}
                    onDeployComplete={onLiveDeploy}
                  />
                </div>
              )}

              {/* Draft deploy — fallback secondary action */}
              <div className="border-t border-border/50 pt-3 space-y-2">
                <p className="text-xs text-muted-foreground text-center font-medium">Or deploy as draft (manual setup)</p>
                {onDeploy && (
                  <Button
                    variant="outline"
                    onClick={onDeploy}
                    disabled={isDeploying}
                    className="w-full gap-2 text-xs"
                    size="sm"
                  >
                    {isDeploying ? (
                      <><RefreshCw className="w-3.5 h-3.5 animate-spin" />Deploying draft...</>
                    ) : (
                      <><Rocket className="w-3.5 h-3.5" />Deploy as Draft to n8n</>
                    )}
                  </Button>
                )}
                {onDownload && (
                  <Button variant="ghost" onClick={onDownload} className="w-full gap-2 text-xs" size="sm">
                    <Download className="w-3.5 h-3.5" />
                    Download Workflow Package
                  </Button>
                )}
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              {onDownload && (
                <Button variant="outline" onClick={onDownload} className="w-full gap-2">
                  <Download className="w-4 h-4" />
                  Download Workflow Package
                </Button>
              )}
              {validation.errors.length > 0 && (
                <p className="text-xs text-muted-foreground text-center">
                  Fix {validation.errors.length} error{validation.errors.length > 1 ? 's' : ''} above before deploying
                </p>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ── MAIN COMPONENT ────────────────────────────────────────────────────────────

const TABS: { id: ArchitectTab; icon: React.ElementType; label: string; description: string }[] = [
  { id: 'plan', icon: Brain, label: 'Plan', description: 'AI-generated automation architecture' },
  { id: 'compose', icon: Layers, label: 'Compose', description: 'Block composition & workflow JSON' },
  { id: 'validate', icon: ShieldCheck, label: 'Validate', description: 'Deployment readiness check' }
];

export function ArchitectPanel({
  plannerResult,
  validation,
  onDeploy,
  onDownload,
  isDeploying,
  deployedUrl,
  deployedWorkflowId,
  deploymentLifecycle,
  onLifecycleChange,
  onCheckActivation,
  isCheckingActivation,
  onLiveDeploy,
  liveDeployResult,
  className,
  isPro = false,
  onUpgrade,
}: ArchitectPanelProps) {
  const [activeTab, setActiveTab] = useState<ArchitectTab>('plan');
  const { plan } = plannerResult;

  const errorCount = validation.errors.length;
  const warningCount = validation.warnings.length;

  // Detect if this workflow has an approval node
  const hasApprovalNode = plan.steps.some(s => s.blockId === 'approval_node');

  return (
    <div className={cn('flex flex-col h-full rounded-xl border border-border bg-card overflow-hidden', className)}>
      {/* Header */}
      <div className="px-4 py-3 border-b border-border bg-muted/20 flex-shrink-0">
        <div className="flex items-center gap-2.5 mb-1">
          <div className="w-7 h-7 rounded-lg bg-primary/20 flex items-center justify-center">
            <Brain className="w-3.5 h-3.5 text-primary" />
          </div>
          <div>
            <h3 className="text-sm font-semibold">Automation Architect</h3>
            <p className="text-xs text-muted-foreground">
              {plan.title} · {plan.estimatedNodes} nodes · {plan.complexity}
            </p>
          </div>
          <div className="ml-auto flex items-center gap-2">
            {errorCount > 0 && (
              <span className="text-xs px-1.5 py-0.5 rounded-full bg-red-500/10 text-red-400 border border-red-500/20">
                {errorCount} error{errorCount > 1 ? 's' : ''}
              </span>
            )}
            {warningCount > 0 && (
              <span className="text-xs px-1.5 py-0.5 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20">
                {warningCount} warning{warningCount > 1 ? 's' : ''}
              </span>
            )}
            {errorCount === 0 && warningCount === 0 && (
              <span className="text-xs px-1.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                Ready
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Tab bar */}
      <div className="flex border-b border-border flex-shrink-0">
        {TABS.map(tab => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                'flex-1 flex items-center justify-center gap-1.5 py-2.5 text-xs font-medium transition-colors border-b-2',
                isActive
                  ? 'border-primary text-foreground'
                  : 'border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/20'
              )}
            >
              <Icon className="w-3.5 h-3.5" />
              {tab.label}
              {tab.id === 'validate' && errorCount > 0 && (
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
              )}
            </button>
          );
        })}
      </div>

      {/* Tab bar — show wizard tab when deployed */}
      {deployedUrl && deployedWorkflowId && deploymentLifecycle && onLifecycleChange && onCheckActivation && (
        <div className="px-4 pb-3 flex-shrink-0 border-b border-border">
          <button
            onClick={() => setActiveTab('validate')}
            className={cn(
              'w-full flex items-center justify-between rounded-lg px-3 py-2 text-xs font-medium border transition-colors',
              activeTab === 'validate'
                ? 'bg-primary/10 border-primary/30 text-primary'
                : 'border-border bg-muted/20 text-muted-foreground hover:text-foreground hover:bg-muted/40'
            )}
          >
            <span className="flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5" />
              Setup Wizard
            </span>
            <span className={cn(
              'text-[10px] px-1.5 py-0.5 rounded-full border',
              deploymentLifecycle === 'active'
                ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                : 'bg-amber-500/10 text-amber-400 border-amber-500/20'
            )}>
              {deploymentLifecycle === 'active' ? 'Active' : 'Setup needed'}
            </span>
          </button>
        </div>
      )}

      {/* Tab content */}
      <div className="flex-1 overflow-y-auto scrollbar-thin p-4">
        {activeTab === 'plan' && <PlanTab plan={plan} />}
        {activeTab === 'compose' && <ComposeTab plannerResult={plannerResult} />}
        {activeTab === 'validate' && deployedUrl && deployedWorkflowId && deploymentLifecycle && onLifecycleChange && onCheckActivation ? (
          <SetupWizard
            workflowName={plan.title}
            workflowUrl={deployedUrl}
            workflowId={deployedWorkflowId}
            credentialsRequired={validation.credentialsRequired}
            hasApprovalNode={hasApprovalNode}
            lifecycle={deploymentLifecycle}
            onLifecycleChange={onLifecycleChange}
            onCheckActivation={onCheckActivation}
            isCheckingActivation={isCheckingActivation}
          />
        ) : activeTab === 'validate' ? (
          <ValidateTab
            validation={validation}
            plannerResult={plannerResult}
            onDeploy={onDeploy}
            onDownload={onDownload}
            isDeploying={isDeploying}
            deployedUrl={deployedUrl}
            onLiveDeploy={onLiveDeploy}
            liveDeployResult={liveDeployResult}
            hasApprovalNode={hasApprovalNode}
            isPro={isPro}
            onUpgrade={onUpgrade}
          />
        ) : null}
      </div>
    </div>
  );
}
