/**
 * MagicFlux Autonomous Agent — Tool Executor
 *
 * Executes tool calls decided by OpenAI. Each tool interacts with real infrastructure.
 */

import {
  activateWorkflow as n8nActivate,
  createWorkflow,
  getWorkflowStatus,
  listExecutions,
  runTestExecution,
  type N8nConfig,
} from '@/lib/ai-engine/n8n-deployer';
import { providerCredentialIsValid } from '@/lib/conversation-agent';
import { requiredProvidersFromWorkflow } from '@/lib/integrations';
import OpenAI from 'openai';
import { recordAgentActionEvent, recordAiUsage } from './observability';
import { withExponentialBackoff, beginDeployTransaction, rollbackWorkflowCreation, updateDeployTransaction } from './recovery';
import { buildWorkflowGraphSummary } from './workflow-graph';
import type { ExecutionPolicy } from './safety';
import { createCorrelationId, emitRuntimeEvent } from '@/lib/runtime/events';
import { enqueueRuntimeJob, runtimeQueueForTool, runtimeTaskTypeForTool } from '@/lib/runtime/queue';
import { getToolExecutionPolicy } from '@/lib/runtime/tool-policy';
import { createTraceId, endSpan, startSpan } from '@/lib/runtime/tracing';
import { createServiceClient } from '@/lib/supabase-server';
import { liveGraphManager } from '@/lib/graph/live-graph-manager';
import { normalizeProvider } from '@/lib/agent/provider-allowlist';
import { getProviderCredentialSchema } from '@/lib/agent/provider-credential-registry';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ToolResult = {
  tool: string;
  success: boolean;
  /** Data to send back as the tool result message */
  output: Record<string, unknown>;
  /** Optional agent-visible event for the UI stream */
  event?: AgentEvent;
  retryCount?: number;
};

export type AgentEventType =
  | 'thinking'
  | 'generating_workflow'
  | 'deploying'
  | 'activating'
  | 'testing'
  | 'requesting_credential'
  | 'explaining_architecture'
  | 'workflow_ready'
  | 'approval_required'
  | 'policy_blocked'
  | 'retrying'
  | 'rolled_back'
  | 'error';

export type AgentEvent = {
  type: AgentEventType;
  label: string;
  detail?: string;
  workflowId?: string;
  workflowUrl?: string;
  agent?: 'planner' | 'integration' | 'deploy' | 'monitoring' | 'recovery';
};

export type ExecutionContext = {
  userId: string | null;
  sessionId: string;
  policy: ExecutionPolicy;
  correlationId?: string;
  traceId?: string;
  parentSpanId?: string;
};

// ---------------------------------------------------------------------------
// n8n config from environment
// ---------------------------------------------------------------------------

function getN8nConfig(): N8nConfig {
  const apiUrl = process.env.N8N_API_URL ?? 'http://localhost:5678';
  const apiKey = process.env.N8N_API_KEY ?? '';
  return { apiUrl, apiKey };
}

function parseWorkflowJson(value: unknown): { nodes: object[]; connections: object } {
  const parsed = JSON.parse(String(value ?? '{}')) as { nodes?: object[]; connections?: object };
  return {
    nodes: Array.isArray(parsed.nodes) ? parsed.nodes : [],
    connections: parsed.connections ?? {},
  };
}

async function ensurePersistedWorkflowDraft(params: {
  userId: string | null;
  sessionId: string;
  args: Record<string, unknown>;
}): Promise<string | null> {
  if (!params.userId) return null;

  const db = createServiceClient();
  const workflowName = String(params.args.workflow_name ?? 'MagicFlux Workflow').trim() || 'MagicFlux Workflow';
  const workflowData = parseWorkflowJson(params.args.workflow_json);
  const workflowJson = {
    nodes: workflowData.nodes,
    connections: workflowData.connections,
  };

  const existingWorkflowId = params.args.workflow_id ? String(params.args.workflow_id).trim() : '';
  let workflowId = existingWorkflowId;

  if (workflowId) {
    const { error } = await db
      .from('workflows')
      .update({
        name: workflowName,
        workflow_json: workflowJson,
        integrations: requiredProvidersFromWorkflow(workflowJson),
        status: 'draft',
        updated_at: new Date().toISOString(),
      })
      .eq('id', workflowId)
      .eq('user_id', params.userId);

    if (error) throw error;
  } else {
    const { data, error } = await db
      .from('workflows')
      .insert({
        user_id: params.userId,
        name: workflowName,
        description: 'Generated by autonomous production deploy flow',
        prompt: workflowName,
        workflow_json: workflowJson,
        integrations: requiredProvidersFromWorkflow(workflowJson),
        status: 'draft',
      })
      .select('id')
      .single();

    if (error) throw error;
    workflowId = String(data.id);
  }

  const graphVersion = await liveGraphManager.createGraphVersion(
    params.userId,
    workflowId,
    workflowJson,
    {
      changesDescription: 'Initial graph persisted before deployment queue dispatch',
      changedBy: 'ai',
    }
  );

  const { error: mutationError } = await db.from('workflow_graph_mutations').insert({
    user_id: params.userId,
    workflow_id: workflowId,
    version: graphVersion.version,
    mutation_type: 'update_node',
    reason: 'Initial workflow graph snapshot before deployment',
    patch: {
      source: 'executor_prequeue',
      node_count: workflowData.nodes.length,
    },
    diff: {
      initialized: true,
      node_count: workflowData.nodes.length,
    },
    created_at: new Date().toISOString(),
  });

  if (mutationError) throw mutationError;

  const { error: conversationUpdateError } = await db
    .from('automation_conversations')
    .update({
      workflow_id: workflowId,
      updated_at: new Date().toISOString(),
    })
    .eq('session_id', params.sessionId)
    .eq('user_id', params.userId);

  if (conversationUpdateError) {
    const message = String(conversationUpdateError.message ?? conversationUpdateError);
    if (!/workflow_id/i.test(message) || !/column/i.test(message)) {
      throw conversationUpdateError;
    }
  }

  params.args.workflow_id = workflowId;
  params.args.workflow_json = JSON.stringify(workflowJson);

  return workflowId;
}

// ---------------------------------------------------------------------------
// Workflow JSON generator — uses OpenAI to build real n8n node JSON
// ---------------------------------------------------------------------------

async function generateWorkflowJson(params: {
  userId: string | null;
  sessionId: string;
  correlationId: string;
  workflow_name: string;
  trigger: string;
  action: string;
  platform: string;
  destination?: string;
  ai_provider?: string;
  schedule?: string;
  automation_style?: string;
  required_capabilities?: string[];
  skill_packs?: string[];
  block_blueprint?: string[];
  nodes_description: string;
}): Promise<{
  nodes: object[];
  connections: object;
  explanation: string;
  usage: { promptTokens: number; completionTokens: number };
}> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY not configured');

  const openai = new OpenAI({ apiKey });

  await emitRuntimeEvent({
    eventType: 'ai.request.started',
    userId: params.userId,
    sessionId: params.sessionId,
    correlationId: params.correlationId,
    agentId: 'deploy',
    payload: { model: 'gpt-4o', purpose: 'generate_workflow_json' },
  });

  const prompt = `You are an expert n8n workflow engineer. Generate a complete, valid n8n workflow JSON for this automation:

Workflow Name: ${params.workflow_name}
Trigger: ${params.trigger}
Action: ${params.action}
Platform: ${params.platform}
${params.destination ? `Destination: ${params.destination}` : ''}
${params.ai_provider ? `AI Provider: ${params.ai_provider}` : ''}
${params.schedule ? `Schedule: ${params.schedule}` : ''}
${params.automation_style ? `Style: ${params.automation_style}` : ''}
${params.required_capabilities && params.required_capabilities.length > 0 ? `Required Capabilities: ${params.required_capabilities.join(', ')}` : ''}
${params.skill_packs && params.skill_packs.length > 0 ? `Activated Skill Packs: ${params.skill_packs.join(', ')}` : ''}
${params.block_blueprint && params.block_blueprint.length > 0 ? `Block Blueprint: ${params.block_blueprint.join(' -> ')}` : ''}
Description: ${params.nodes_description}

Return a JSON object with this exact structure:
{
  "nodes": [ /* array of valid n8n node objects */ ],
  "connections": { /* n8n connections map */ },
  "explanation": "Clear 4-6 step numbered explanation of how this workflow operates"
}

Use real n8n node types (e.g. n8n-nodes-base.gmailTrigger, n8n-nodes-base.openAi, etc.).
Each node must have: id, name, type, typeVersion, position [x,y], parameters, displayName, provider.
For provider use canonical ids (openai, facebook, canva, telegram, google_sheets, twitter, claude, deepgram, reddit, airtable, slack, supabase, coinmarketcap, whatsapp, email, shopify, stripe) or null.
Do not emit credentialSchema or credential defaults; provider credentialSchema is hydrated server-side from canonical providerCredentialRegistry.
Do not emit generic provider placeholders; attach provider metadata directly on every node.
Keep it production-ready and deployable.`;

  const response = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0.1,
    max_tokens: 3000,
  });

  const raw = response.choices[0]?.message?.content ?? '{}';
  const parsed = JSON.parse(raw) as {
    nodes?: object[];
    connections?: object;
    explanation?: string;
  };

  const normalizedNodes = (Array.isArray(parsed.nodes) ? parsed.nodes : []).map((rawNode) => {
    const node = { ...(rawNode as Record<string, unknown>) };
    const providerMeta = typeof node.parameters === 'object' && node.parameters !== null
      ? ((node.parameters as Record<string, unknown>).providerMeta as Record<string, unknown> | undefined)
      : undefined;
    const rawProvider =
      (typeof node.provider === 'string' ? node.provider : undefined)
      ?? (typeof node.integration === 'string' ? node.integration : undefined)
      ?? (typeof providerMeta?.provider === 'string' ? providerMeta.provider : undefined)
      ?? '';
    const normalizedProvider = normalizeProvider(rawProvider);
    const provider = normalizedProvider && normalizedProvider !== 'core' && normalizedProvider !== 'integration'
      ? normalizedProvider
      : null;

    const credentialSchema = getProviderCredentialSchema(provider);
    const requiresCredentials = credentialSchema.length > 0;

    return {
      ...node,
      displayName: String(node.displayName ?? node.name ?? 'Workflow Node'),
      provider,
      requiresCredentials,
      credentialSchema,
    };
  });

  await emitRuntimeEvent({
    eventType: 'ai.request.completed',
    userId: params.userId,
    sessionId: params.sessionId,
    correlationId: params.correlationId,
    agentId: 'deploy',
    payload: {
      model: 'gpt-4o',
      prompt_tokens: response.usage?.prompt_tokens ?? 0,
      completion_tokens: response.usage?.completion_tokens ?? 0,
    },
  });

  return {
    nodes: normalizedNodes,
    connections: parsed.connections ?? {},
    explanation: typeof parsed.explanation === 'string' ? parsed.explanation : 'Workflow generated.',
    usage: {
      promptTokens: response.usage?.prompt_tokens ?? 0,
      completionTokens: response.usage?.completion_tokens ?? 0,
    },
  };
}

// ---------------------------------------------------------------------------
// Tool executor — maps tool name → real implementation
// ---------------------------------------------------------------------------

export async function executeTool(
  toolName: string,
  args: Record<string, unknown>,
  ctx: ExecutionContext
): Promise<ToolResult> {
  const n8n = getN8nConfig();
  const startedAt = Date.now();
  const correlationId = ctx.correlationId ?? createCorrelationId(ctx.sessionId);
  const traceId = ctx.traceId ?? createTraceId();
  const executionId = `${toolName}-${Date.now()}`;
  const toolSpanId = await startSpan({
    userId: ctx.userId,
    traceId,
    parentSpanId: ctx.parentSpanId,
    name: `tool:${toolName}`,
    kind: 'tool',
    agentId: 'runtime',
    sessionId: ctx.sessionId,
    workflowId: args.workflow_id ? String(args.workflow_id) : undefined,
    executionId,
    attributes: { args },
  });
  let failed = false;

  await recordAgentActionEvent({
    userId: ctx.userId,
    sessionId: ctx.sessionId,
    eventType: 'tool_started',
    actionName: toolName,
    status: 'info',
    detail: `Starting ${toolName}`,
    metadata: { args },
  });

  await emitRuntimeEvent({
    eventType: 'tool.started',
    userId: ctx.userId,
    sessionId: ctx.sessionId,
    workflowId: args.workflow_id ? String(args.workflow_id) : undefined,
    executionId,
    correlationId,
    traceId,
    spanId: toolSpanId,
    parentSpanId: ctx.parentSpanId,
    agentId: 'runtime',
    payload: { toolName, args },
  });

  try {
    const toolPolicy = getToolExecutionPolicy(toolName);
    const shouldQueue = ['deploy_workflow_to_n8n', 'activate_workflow', 'test_workflow'].includes(toolName);

    if (shouldQueue) {
      if (toolName === 'deploy_workflow_to_n8n') {
        try {
          await ensurePersistedWorkflowDraft({
            userId: ctx.userId,
            sessionId: ctx.sessionId,
            args,
          });
        } catch (error) {
          const message = error instanceof Error ? error.message : 'Failed to persist workflow before deployment';
          return {
            tool: toolName,
            success: false,
            output: {
              error_code: 'WORKFLOW_PERSISTENCE_FAILED',
              error: message,
              queued: false,
            },
            event: {
              type: 'error',
              label: 'I could not persist the workflow before deployment',
              detail: 'Please retry. If it happens again, check workflow/graph persistence tables.',
              agent: 'recovery',
            },
          };
        }
      }

      const queued = await enqueueRuntimeJob({
        queueName: runtimeQueueForTool(toolName),
        taskType: runtimeTaskTypeForTool(toolName),
        payload: {
          userId: ctx.userId,
          sessionId: ctx.sessionId,
          workflowId: args.workflow_id ? String(args.workflow_id) : undefined,
          toolName,
          policyMode: ctx.policy.mode,
          args,
          correlationId,
          executionId,
          traceId,
          parentSpanId: toolSpanId,
        },
        attempts: toolPolicy.retry.attempts + 1,
      });

      if (!queued.enqueued) {
        return {
          tool: toolName,
          success: false,
          output: {
            error_code: 'RUNTIME_NOT_CONFIGURED',
            error: queued.reason ?? 'Queue unavailable',
            queued: false,
          },
          event: {
            type: 'error',
            label: 'I could not start execution right now',
            detail: queued.reason ? 'Runtime is temporarily unavailable. Please retry in a moment.' : undefined,
            agent: 'recovery',
          },
        };
      }

      const queuedLabel =
        toolName === 'deploy_workflow_to_n8n'
          ? 'Deploying your automation...'
          : toolName === 'activate_workflow'
            ? 'Activating your automation...'
            : 'Testing your automation...';

      const queuedDetail =
        toolName === 'deploy_workflow_to_n8n'
          ? 'Deployment has started in the background.'
          : toolName === 'activate_workflow'
            ? 'Activation is running in the background.'
            : 'Test run is being prepared.';

      return {
        tool: toolName,
        success: true,
        output: {
          queued: true,
          queue_job_id: queued.queueJobId,
          queue: runtimeQueueForTool(toolName),
          execution_id: executionId,
          correlation_id: correlationId,
          message: `${toolName} queued for deterministic runtime worker execution`,
        },
        event: {
          type: toolName === 'deploy_workflow_to_n8n' ? 'deploying' : toolName === 'activate_workflow' ? 'activating' : 'testing',
          label: queuedLabel,
          detail: queuedDetail,
          agent: 'deploy',
        },
      };
    }

    switch (toolName) {
      // -----------------------------------------------------------------------
      case 'generate_workflow_json': {
        const requiredCapabilities = Array.isArray(args.required_capabilities)
          ? args.required_capabilities.map((value) => String(value).trim()).filter(Boolean)
          : [];
        const skillPacks = Array.isArray(args.skill_packs)
          ? args.skill_packs.map((value) => String(value).trim()).filter(Boolean)
          : [];
        const blockBlueprint = Array.isArray(args.block_blueprint)
          ? args.block_blueprint.map((value) => String(value).trim()).filter(Boolean)
          : [];

        const result = await generateWorkflowJson({
          userId: ctx.userId,
          sessionId: ctx.sessionId,
          correlationId,
          workflow_name: String(args.workflow_name ?? 'My Workflow'),
          trigger: String(args.trigger ?? ''),
          action: String(args.action ?? ''),
          platform: String(args.platform ?? ''),
          destination: args.destination ? String(args.destination) : undefined,
          ai_provider: args.ai_provider ? String(args.ai_provider) : undefined,
          schedule: args.schedule ? String(args.schedule) : undefined,
          automation_style: args.automation_style ? String(args.automation_style) : undefined,
          required_capabilities: requiredCapabilities,
          skill_packs: skillPacks,
          block_blueprint: blockBlueprint,
          nodes_description: String(args.nodes_description ?? ''),
        });

        await recordAiUsage({
          userId: ctx.userId,
          sessionId: ctx.sessionId,
          provider: 'openai',
          model: 'gpt-4o',
          agentName: 'deploy',
          promptTokens: result.usage.promptTokens,
          completionTokens: result.usage.completionTokens,
          metadata: { tool: toolName },
        });

        const workflowGraph = buildWorkflowGraphSummary({
          nodes: result.nodes,
          connections: result.connections,
        });

        const toolResult: ToolResult = {
          tool: toolName,
          success: true,
          output: {
            workflow_json: JSON.stringify({ nodes: result.nodes, connections: result.connections }),
            explanation: result.explanation,
            node_count: result.nodes.length,
            workflow_graph: workflowGraph,
          },
          event: {
            type: 'generating_workflow',
            label: `Workflow blueprint generated`,
            detail: `${result.nodes.length} nodes — ${String(args.workflow_name)}`,
            agent: 'deploy',
          },
        };

        await recordAgentActionEvent({
          userId: ctx.userId,
          sessionId: ctx.sessionId,
          eventType: 'tool_completed',
          actionName: toolName,
          status: 'success',
          detail: 'Workflow JSON generated',
          durationMs: Date.now() - startedAt,
          metadata: { nodeCount: result.nodes.length },
        });

        return toolResult;
      }

      // -----------------------------------------------------------------------
      case 'deploy_workflow_to_n8n': {
        let workflowData: { nodes: object[]; connections: object };
        try {
          workflowData = JSON.parse(String(args.workflow_json ?? '{}')) as typeof workflowData;
        } catch {
          return {
            tool: toolName,
            success: false,
            output: { error: 'Invalid workflow JSON' },
          };
        }

        const workflowName = String(args.workflow_name ?? 'MagicFlux Workflow');

        const deployTransactionId = await beginDeployTransaction({
          userId: ctx.userId,
          sessionId: ctx.sessionId,
          workflowName,
          dryRun: ctx.policy.dryRunEnabled,
          sandbox: ctx.policy.sandboxEnabled,
          snapshotBefore: { workflowName, mode: ctx.policy.mode },
        });

        if (ctx.policy.mode !== 'production' && ctx.policy.dryRunEnabled) {
          await updateDeployTransaction({
            transactionId: deployTransactionId,
            patch: {
              status: 'deployed',
              snapshot_after: {
                dry_run: true,
                workflow_name: workflowName,
                estimated_nodes: Array.isArray(workflowData.nodes) ? workflowData.nodes.length : 0,
              },
              completed_at: new Date().toISOString(),
            },
          });

          return {
            tool: toolName,
            success: true,
            output: {
              workflow_id: `dryrun-${Date.now()}`,
              workflow_url: null,
              status: 'draft',
              dry_run: true,
              sandbox: ctx.policy.sandboxEnabled,
            },
            event: {
              type: 'deploying',
              label: 'Dry-run deploy prepared',
              detail: 'No external deploy executed due to safety policy',
              agent: 'deploy',
            },
          };
        }

        const deployAttempt = await withExponentialBackoff(
          async () => createWorkflow(n8n, {
            name: workflowName,
            nodes: workflowData.nodes ?? [],
            connections: workflowData.connections ?? {},
            settings: { executionOrder: 'v1' },
            active: false,
          }),
          { retries: 2, baseDelayMs: 600, maxDelayMs: 4000 }
        );

        const deployResult = deployAttempt.value;

        if (!deployResult) {
          await updateDeployTransaction({
            transactionId: deployTransactionId,
            patch: {
              status: 'failed',
              error_message: deployAttempt.error ?? 'Deploy failed after retries',
              completed_at: new Date().toISOString(),
            },
          });

          return {
            tool: toolName,
            success: false,
            output: {
              error: deployAttempt.error ?? 'Deploy failed after retries',
              recovery_suggestion: 'Check n8n connectivity and API key, then retry deploy.',
            },
            event: {
              type: 'error',
              label: 'Deploy failed',
              detail: deployAttempt.error,
              agent: 'deploy',
            },
            retryCount: Math.max(0, deployAttempt.attempts - 1),
          };
        }

        if (deployResult.status === 'error') {
          await updateDeployTransaction({
            transactionId: deployTransactionId,
            patch: {
              status: 'failed',
              error_message: deployResult.error ?? 'Deploy failed',
              completed_at: new Date().toISOString(),
            },
          });

          return {
            tool: toolName,
            success: false,
            output: {
              error: deployResult.error ?? 'Deploy failed',
              recovery_suggestion: 'Validate workflow nodes and n8n endpoint, then retry.',
            },
            event: {
              type: 'error',
              label: 'Deploy failed',
              detail: deployResult.error,
              agent: 'deploy',
            },
            retryCount: Math.max(0, deployAttempt.attempts - 1),
          };
        }

        await updateDeployTransaction({
          transactionId: deployTransactionId,
          patch: {
            status: 'deployed',
            workflow_id: deployResult.workflowId,
            snapshot_after: {
              workflow_id: deployResult.workflowId,
              workflow_url: deployResult.workflowUrl,
              status: deployResult.status,
            },
            completed_at: new Date().toISOString(),
          },
        });

        return {
          tool: toolName,
          success: true,
          output: {
            workflow_id: deployResult.workflowId,
            workflow_url: deployResult.workflowUrl,
            status: deployResult.status,
          },
          event: {
            type: 'deploying',
            label: 'Workflow deployed successfully',
            detail: 'Deployment finished and ready for activation.',
            workflowId: deployResult.workflowId,
            workflowUrl: deployResult.workflowUrl,
            agent: 'deploy',
          },
          retryCount: Math.max(0, deployAttempt.attempts - 1),
        };
      }

      // -----------------------------------------------------------------------
      case 'activate_workflow': {
        const workflowId = String(args.workflow_id ?? '');
        if (!workflowId) {
          return {
            tool: toolName,
            success: false,
            output: { error: 'workflow_id is required' },
            event: { type: 'error', label: 'Activation failed', detail: 'Missing workflow id', agent: 'deploy' },
          };
        }

        const activateAttempt = await withExponentialBackoff(
          async () => {
            await n8nActivate(n8n, workflowId);
            return { ok: true };
          },
          { retries: 2, baseDelayMs: 700, maxDelayMs: 4500 }
        );

        if (!activateAttempt.value) {
          const rollbackRequested = ctx.policy.mode !== 'production' || args.rollback_on_failure === true;
          let rollbackResult: { rolledBack: boolean; message: string } | undefined;
          if (rollbackRequested) {
            rollbackResult = await rollbackWorkflowCreation({ n8n, workflowId });
          }

          return {
            tool: toolName,
            success: false,
            output: {
              error: activateAttempt.error ?? 'Activation failed',
              rollback: rollbackResult ?? null,
              recovery_suggestion: 'Check n8n workflow credentials and trigger node configuration.',
            },
            event: {
              type: rollbackResult?.rolledBack ? 'rolled_back' : 'error',
              label: rollbackResult?.rolledBack ? 'Activation failed, rollback completed' : 'Activation failed',
              detail: rollbackResult?.message ?? activateAttempt.error,
              workflowId,
              agent: rollbackResult?.rolledBack ? 'recovery' : 'deploy',
            },
            retryCount: Math.max(0, activateAttempt.attempts - 1),
          };
        }

        return {
          tool: toolName,
          success: true,
          output: { workflow_id: workflowId, active: true },
          event: {
            type: 'activating',
            label: 'Workflow activated',
            detail: 'The automation is now listening for triggers.',
            workflowId,
            agent: 'deploy',
          },
          retryCount: Math.max(0, activateAttempt.attempts - 1),
        };
      }

      // -----------------------------------------------------------------------
      case 'test_workflow': {
        const workflowId = String(args.workflow_id ?? '');
        const result = await runTestExecution(
          n8n,
          workflowId,
          args.trigger_node ? String(args.trigger_node) : undefined
        );

        return {
          tool: toolName,
          success: result.status === 'success',
          output: {
            execution_id: result.executionId,
            status: result.status,
            message: result.message,
            node_statuses: result.nodeStatuses,
            started_at: result.startedAt,
            stopped_at: result.stoppedAt,
          },
          event: {
            type: result.status === 'success' ? 'testing' : 'error',
            label: result.status === 'success' ? 'Test execution passed' : 'Test execution failed',
            detail: result.message,
            workflowId,
            agent: 'monitoring',
          },
        };
      }

      // -----------------------------------------------------------------------
      case 'validate_credential': {
        const provider = String(args.provider ?? '');
        const value = String(args.credential_value ?? '');
        const valid = providerCredentialIsValid(provider, value);

        return {
          tool: toolName,
          success: true,
          output: {
            provider,
            valid,
            message: valid
              ? `${provider} credential is valid`
              : `${provider} credential format is invalid — please check and try again`,
          },
        };
      }

      // -----------------------------------------------------------------------
      case 'get_workflow_status': {
        const workflowId = String(args.workflow_id ?? '');
        const status = await getWorkflowStatus(n8n, workflowId);

        return {
          tool: toolName,
          success: true,
          output: {
            workflow_id: status.id,
            name: status.name,
            active: status.active,
            created_at: status.createdAt,
            updated_at: status.updatedAt,
          },
        };
      }

      // -----------------------------------------------------------------------
      case 'get_execution_logs': {
        const workflowId = String(args.workflow_id ?? '');
        const limit = typeof args.limit === 'number' ? args.limit : 5;
        const executions = await listExecutions(n8n, workflowId, limit);

        return {
          tool: toolName,
          success: true,
          output: {
            executions: executions.map((e) => ({
              id: e.id,
              status: e.status,
              started_at: e.startedAt,
              stopped_at: e.stoppedAt,
              finished: e.finished,
            })),
          },
        };
      }

      // -----------------------------------------------------------------------
      case 'explain_workflow_architecture': {
        const steps = Array.isArray(args.steps) ? (args.steps as string[]) : [];
        const integrations = Array.isArray(args.integrations_required)
          ? (args.integrations_required as string[])
          : [];

        const explanation =
          `Here is how your **${String(args.workflow_name)}** automation will work:\n\n` +
          steps.map((s, i) => `${i + 1}. ${s}`).join('\n') +
          (integrations.length > 0
            ? `\n\n**Integrations needed:** ${integrations.join(', ')}`
            : '');

        return {
          tool: toolName,
          success: true,
          output: { explanation, steps, integrations_required: integrations },
          event: {
            type: 'explaining_architecture',
            label: 'Architecture ready',
            detail: `${steps.length} steps`,
            agent: 'planner',
          },
        };
      }

      // -----------------------------------------------------------------------
      case 'request_credential': {
        const provider = String(args.provider ?? '');
        const reason = String(args.reason ?? '');
        const instructions = args.instructions ? String(args.instructions) : undefined;

        return {
          tool: toolName,
          success: true,
          output: {
            provider,
            reason,
            instructions,
            awaiting_credential: true,
          },
          event: {
            type: 'requesting_credential',
            label: `Need ${provider} credentials`,
            detail: reason,
            agent: 'integration',
          },
        };
      }

      // -----------------------------------------------------------------------
      default:
        return {
          tool: toolName,
          success: false,
          output: { error: `Unknown tool: ${toolName}` },
        };
    }
  } catch (err) {
    failed = true;
    const message = err instanceof Error ? err.message : String(err);
    await recordAgentActionEvent({
      userId: ctx.userId,
      sessionId: ctx.sessionId,
      eventType: 'tool_failed',
      actionName: toolName,
      status: 'error',
      detail: message,
      durationMs: Date.now() - startedAt,
      errorCode: 'TOOL_RUNTIME_ERROR',
    });
    return {
      tool: toolName,
      success: false,
      output: { error: message },
      event: { type: 'error', label: 'I hit an execution error', detail: message },
    };
  } finally {
    await emitRuntimeEvent({
      eventType: failed ? 'tool.failed' : 'tool.completed',
      userId: ctx.userId,
      sessionId: ctx.sessionId,
      workflowId: args.workflow_id ? String(args.workflow_id) : undefined,
      executionId,
      correlationId,
      traceId,
      spanId: toolSpanId,
      parentSpanId: ctx.parentSpanId,
      agentId: 'runtime',
      severity: failed ? 'error' : 'info',
      payload: { toolName, duration_ms: Date.now() - startedAt },
    });

    await endSpan({
      userId: ctx.userId,
      spanId: toolSpanId,
      status: failed ? 'error' : 'success',
      errorMessage: failed ? `${toolName} failed` : undefined,
      attributes: { duration_ms: Date.now() - startedAt, toolName },
    });

    await recordAgentActionEvent({
      userId: ctx.userId,
      sessionId: ctx.sessionId,
      eventType: 'tool_finished',
      actionName: toolName,
      status: 'info',
      durationMs: Date.now() - startedAt,
    });
  }
}
