'use client';

import { useCallback, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Loader2 } from 'lucide-react';

import { Button }   from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { AiWorkflowGeneratorPanel } from '@/components/ai-workflows/AiWorkflowGeneratorPanel';

interface GeneratedWorkflow {
  name:        string;
  nodes:       Array<{ name: string; type: string; parameters?: Record<string, unknown> }>;
  connections: Record<string, unknown>;
}

export default function NewAiWorkflowPage() {
  const router  = useRouter();
  const [saving,    setSaving   ] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  /**
   * Called by AiWorkflowGeneratorPanel when the user clicks "Use this workflow".
   * Saves the workflow to the database then redirects to the detail page.
   * The detail page (/dashboard/workflows/[id]) renders the full workflow_json,
   * node count, integrations, and exposes test/deploy buttons.
   */
  const handleWorkflowGenerated = useCallback(async (workflow: GeneratedWorkflow) => {
    setSaving(true);
    setSaveError(null);

    try {
      const res = await fetch('/api/workflows', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({
          name:          workflow.name || 'AI Generated Workflow',
          description:   `Generated by AI Workflow Generator`,
          workflow_json: workflow,
        }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({})) as { error?: string };
        if (res.status === 429) {
          setSaveError(data.error ?? 'Workflow limit reached. Please upgrade your plan.');
          return;
        }
        setSaveError(data.error ?? 'Could not save workflow. Please try again.');
        return;
      }

      const data = await res.json() as { workflow?: { id?: string } };
      const id = data.workflow?.id;
      if (!id) {
        setSaveError('Workflow saved but ID was not returned. Please check your dashboard.');
        router.push('/dashboard');
        return;
      }

      // Redirect to the existing workflow detail page which loads workflow_json,
      // renders node count + integrations visually, and provides test/deploy.
      router.push(`/dashboard/workflows/${id}`);
    } catch {
      setSaveError('Network error. Please check your connection and try again.');
    } finally {
      setSaving(false);
    }
  }, [router]);

  return (
    <div className="min-h-screen bg-background">
      {/* Top nav */}
      <header className="border-b">
        <div className="mx-auto max-w-3xl px-4 py-3 flex items-center gap-3">
          <Button variant="ghost" size="icon" asChild>
            <Link href="/dashboard">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <span className="text-sm font-medium text-foreground">New AI Workflow</span>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-4 py-8 space-y-6">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Generate a workflow</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Describe your automation in plain English. Click{' '}
            <strong>Use this workflow</strong> to save it and open the editor.
          </p>
        </div>

        {/* Save error */}
        {saveError && (
          <Alert variant="destructive">
            <AlertDescription>{saveError}</AlertDescription>
          </Alert>
        )}

        {/* Saving overlay indicator */}
        {saving && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            Saving workflow…
          </div>
        )}

        {/* Generator panel — "Use this workflow" triggers save+redirect */}
        <AiWorkflowGeneratorPanel
          onWorkflowGenerated={handleWorkflowGenerated}
          disabled={saving}
        />
      </main>
    </div>
  );
}
